remote_theme: just-the-docs/just-the-docs@v0.11.1
plugins:
- jekyll-remote-theme
- jemoji

title: Git Starter
description: Getting started with git.

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/starter-cookbook/git-starter"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

nav_external_links:
  - title: Issues
    url: https://github.com/starter-cookbook/git-starter/issues
    hide_icon: false
    opens_in_new_tab: true
  - title: Discussions
    url: https://github.com/starter-cookbook/git-starter/discussions
    hide_icon: false
    opens_in_new_tab: true

color_scheme: wider

callouts:
  warning:
    title: Warning
    color: red
